services:
  database:
    container_name: kopjum-db
    image: postgres:14-alpine
    restart: 'no'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=12345678
      - POSTGRES_DB=kopjum
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - '5443:5432'

volumes:
  database:
